@startuml
skinparam shadowing false
skinparam defaultFontName Arial

start

:Запуск программы;
:Создание объекта Sudoku;
:Генерация полного решения;
:Удаление клеток;
:Проверка единственности решения;
:Вывод игрового поля;

while (Поле заполнено?) is (Нет)
    :Ввод строки, столбца и числа;

    if (Пользователь ввел 0 0 0?) then (Да)
        :Выход из игры;
        stop
    else (Нет)
    endif

    if (Клетка доступна?) then (Да)
        if (Число можно поставить?) then (Да)
            :Поставить число в клетку;
            :Вывести сообщение\n"Ход сделан";
        else (Нет)
            :Вывести сообщение\n"Такой ход невозможен";
        endif
    else (Нет)
        :Вывести сообщение\n"Клетку нельзя изменить";
    endif

    :Вывод игрового поля;
endwhile (Да)

if (Решение совпадает\nс solution[9][9]?) then (Да)
    :Победа;
else (Нет)
    :Ошибка в решении;
endif

stop
@enduml